name: HackerNewsWatch
options:
  minimumXcodeGenVersion: 2.38.0
  developmentLanguage: en
  groupSortPosition: top
  createIntermediateGroups: true

targets:
  HackerNewsWatch Watch App:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: Sources/WatchApp
    dependencies: []
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.HackerNewsWatch.watchapp
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Sources/WatchApp/Info.plist
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []

  HackerNewsWatch Widget Extension:
    type: app-extension
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: Sources/WidgetExtension
    dependencies:
      - target: HackerNewsWatch Watch App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.HackerNewsWatch.watchapp.widget
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Sources/WidgetExtension/Info.plist
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        SKIP_INSTALL: YES
    scheme:
      testTargets: []

packages: {}

attributes:
  ORGANIZATIONNAME: Example
