# This workflow will build the Xcode (watchOS) project using XcodeGen and xcodebuild
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Xcode project
      run: bash ./scripts/generate.sh
    - name: Build watchOS app
      run: bash ./scripts/build.sh
