# This workflow will build the Xcode (watchOS) project using XcodeGen and xcodebuild
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version (latest stable)
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Show selected Xcode version
      run: xcodebuild -version
    - name: Generate Xcode project
      run: bash ./scripts/generate.sh
    - name: Build watchOS app
      run: bash ./scripts/build.sh
    - name: Package app artifacts
      run: bash ./scripts/package.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: watchos-app-artifacts
        path: artifacts/*.zip
        if-no-files-found: error
    - name: Create GitHub Release and upload assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          artifacts/*.zip
